project:
  type: website
  output-dir: docs
  #pre-render: utils/export_all_diagrams.py
  #post-render: utils/export_all_diagrams.py --clean

lang: es

website:
  title: "Courseware Eng"
  description: "Guías, presentaciones y prácticas de laboratorio para cursos de ingeniería: programación, instrumentación, automatización industrial y documentación por código."
  
  # Barra superior (Menú principal)
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: guides/index.qmd
        text: "Guías"
      - href: slides/index.qmd
        text: "Presentaciones"             
      - href: labs/index.qmd
        text: "Prácticas"
    right:
      - href: info/about.qmd
        text: "Acerca de"

  # Barra lateral
  sidebar:
    id: guias-sidebar
    title: "Contenido"
    style: "docked"  
    search: true     
    contents:
      - section: "Material de Apoyo"
        contents:
          - "guides"
          - "slides"
          - "labs"
  
execute:
  freeze: auto

format:
  html:
    theme: cosmo     
    toc: true        

embed-resources: true