---
title: "Courseware Eng"
---

Esta es la página principal del proyecto. Aquí centralizamos todo el conocimiento y los recursos visuales disponibles para los cursos de ingeniería: programación en Python, instrumentación industrial, automatización y documentación por código.

:::: {.grid}

::: {.g-col-12 .g-col-md-6}

## 📚 Guías de Usuario
Consulta nuestra documentación detallada para aprender a instalar, configurar y utilizar las herramientas.

- Pasos claros y concisos.
- Imagenes con el paso a paso.
- Solución de problemas comunes.

[Ir a las Guías &rarr;](guides/index.qmd){.btn .btn-primary role="button"}

:::

::: {.g-col-12 .g-col-md-6}

## 📊 Presentaciones
Material visual utilizado en nuestras demos y reuniones. Perfecto para tener una visión general rápida.

- Diapositivas interactivas.
- Formato RevealJS.
- Accesible desde cualquier navegador.

[Ir a las Presentaciones &rarr;](slides/index.qmd){.btn .btn-primary role="button"}

:::

::: {.g-col-12 .g-col-md-6}

## 📊 Prácticas
Guías utilizadas para la realización de experimentos y simulaciones.

- Simulaciones interactivas.
- Enlaces a herramientas de simulación.
- Accesible desde cualquier navegador.

[Ir a las Prácticas &rarr;](labs/index.qmd){.btn .btn-primary role="button"}

:::


::::

---

::: {.callout-note}
## Novedades
El repositorio se actualizará con nuevas guías, presentaciones y prácticas de laboratorio y simulación.
:::