---
title: "Índice de Guías."
---

Esta es la página principal de Guías. Encontrará listadas las asignaturas, seleccione una para continuar.

:::: {.grid}

::: {.g-col-12 .g-col-md-6}
## 📚 Guías de Automatización
Consulta nuestra documentación detallada para aprender a instalar, configurar y utilizar las herramientas del curso de Automatización Industrial.
[Ir a las Guías &rarr;](automation/index.qmd){.btn .btn-primary role="button"}
:::

::: {.g-col-12 .g-col-md-6}
## 📚 Guías de Documentación por Código.
Consulta nuestra documentación detallada para aprender a instalar, configurar y utilizar herramientas para documentación técnica usando código.
[Ir a las Guías &rarr;](documentation/index.qmd){.btn .btn-primary role="button"}
:::

::: {.g-col-12 .g-col-md-6}
## 📚 Guías de Programación en Python.
Consulta nuestra documentación detallada para aprender a programar con Python y VSCode.
[Ir a las Guías &rarr;](programming/index.qmd){.btn .btn-primary role="button"}
:::

::: {.g-col-12 .g-col-md-6}
## 📚 Guías de Robótica.
Consulta nuestra documentación detallada para aprender algunos fundamentos sobre robotica con ROS2.
[Ir a las Guías &rarr;](robotics/index.qmd){.btn .btn-primary role="button"}
:::

::: {.g-col-12 .g-col-md-6}
## 📚 Procedimientos académicos.
Documentos de procedimientos académicos, como el de Trabajo de Grado.
[Ir a los Procedimientos &rarr;](tgs/index.qmd){.btn .btn-primary role="button"}
:::

::::

---